services:
    app:
        container_name: projectdyl-app
        image: projectdyl_app_image
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            APP_DATABASE_ENV: local
        build:
            dockerfile: docker/Dockerfile
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app/app
            - ./config:/app/config
            - ./database:/app/database
            - ./resources:/app/resources
            - ./routes:/app/routes
            - ./tests:/app/tests
            - ./storage:/app/storage
            - ./composer.json:/app/composer.json
            - ./composer.lock:/app/composer.lock
            - ./.env:/app/.env:ro
            - ./.githooks:/app/.githooks:ro
        depends_on:
            mariadb:
                condition: service_healthy
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - projectDYL

    mariadb:
        container_name: projectdyl-mariadb
        image: mariadb:10.9
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            APP_DATABASE_ENV: local
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysql", "-uroot", "-psecret", "-e", "SELECT 1;" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - projectDYL

volumes:
    mariadb_data:

networks:
    projectDYL:
        name: projectDYL
